db:
  dsn: 'root:root@tcp(127.0.0.1:3306)/butterfly_admin?charset=utf8mb4&parseTime=True&loc=Local'

server:
  engineMode: 'release'
  serverAddr: :8081

auth:
  ignorePath:
  ignorePrefixPath:
  commonPath:
    - GET - /api/sys/menu/withOption
    - GET - /api/sys/role/all
    - GET - /api/sys/user/all